//AUTH USER LOGIN
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_COMPLETED = "USER_LOGIN_COMPLETED";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";
export const USER_LOGOUT = "USER_LOGOUT";

//AUTH USER REGISTER
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_COMPLETED = "USER_REGISTER_COMPLETED";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";


//FETCH PRODUCT
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_COMPLETED = 'GET_PRODUCTS_COMPLETED';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

//FETCH API IMAGES
export const GET_PEXELS_IMAGES = 'GET_PEXELS_IMAGES';
export const GET_PEXELS_IMAGES_REQUEST = 'GET_PEXELS_IMAGES_REQUEST';
export const GET_PEXELS_IMAGES_COMPLETED = 'GET_PEXELS_IMAGES_COMPLETED';
export const GET_PEXELS_IMAGES_ERROR = 'GET_PEXELS_IMAGES_ERROR';